source 'http://rubygems.org'


gem 'rails', '4.2.4'

gem 'rails-api'

gem 'spring', :group => :development

group :development , :test do
	gem 'rspec-rails' , '~> 3.0'
  gem 'sqlite3'
  gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]
end

gem 'gcm'

gem 'certified'

group :production do
  gem 'pg'
  gem 'rails_12factor'
end

gem 'sidekiq'

# To use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

ruby '2.2.3'
