source 'http://rubygems.org'

gem 'rails', '4.2.4'

gem 'rails-api'

group :development , :test do
  gem 'spring'
	gem 'rspec-rails' , '~> 3.0'
  gem 'sqlite3'
  gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]
end

gem 'gcm'

gem 'certified'

group :production do
  gem 'pg'
  gem 'rails_12factor'
  gem 'puma'
end

gem 'sidekiq'

# To use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'
