# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e071642d35786fdd8eca9a5817fa1930666e56e102c614e42405fa6f5733e8d66c88c4a38ed7ab7b466018569d694351157bebe4da3f2da11227ee633eaa320

test:
  secret_key_base: 4b3b85cfb3f8a488904e1ae895a6334d9dee4dc22cfc593473355b9d72141e811c53d3d3effe9367798bb0296c9843b55cfdebacee65643f469731f889f8bf74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
